- hosts: all
  user: ansible

  tasks:
    - name: Get uptime
      shell: uptime
      register: uptime_result
      changed_when: "uptime_result.rc != 0"

    - debug: { 
        msg: "Uptime for {{ ansible_hostname }}: {{ uptime_result.stdout }}"
      }
